name: outer-call

on:
  workflow_dispatch:
jobs:
  outer-call:
    permissions:
      contents: write
      pull-requests: write
    uses: ./.github/workflows/sync.yml
    # without the serets inherit I get an error because I use ${secrets.PAT} within the called workflow
    # secrets: inherit
